modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="josephcore"
version="1.0.5"
displayName="JosephCore"
credits="Joseph's Core Mod, contains essence of EmeraldTNT!"
displayURL="https://josephworks.github.io"
logoFile="logo.png"
authors="Joseph Robinson"
description='''
Joseph's Core Mod
'''

[[dependencies.josephcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



